### ISSUE TITLE
--add erroring out on mac

### ISSUE THREAD

**Issue by jonashaefele** [jamescooke/chattydotfiles#4] opened 2015-02-20 12:10 UTC
```
~/dotfiles/store   master  la
total 40
-rw-r--r--  1 jonas  staff  1702 20 Feb 12:03 .aliases
-rw-r--r--  1 jonas  staff    47 14 Apr  2014 .bashrc
-rw-r--r--  1 jonas  staff   193 20 Feb 12:02 .gitconfig
-rw-r--r--  1 jonas  staff   137  7 Jul  2014 .zshenv
-rw-r--r--  1 jonas  staff  2376 19 Feb 11:43 .zshrc
 ~/dotfiles/store   master  chattydotfiles --add .zshrc
[INFO] Found /Users/jonas/dotfiles/store

Traceback (most recent call last):
  File "/usr/local/bin/chattydotfiles", line 9, in <module>
    load_entry_point('chattydotfiles==0.2', 'console_scripts', 'chattydotfiles')()
  File "/Library/Python/2.7/site-packages/chattydotfiles/command_line.py", line 19, in main
    return cc.add(args.add)
  File "/Library/Python/2.7/site-packages/chattydotfiles/command_line.py", line 76, in add
    self.repository.add(abs_new_filename)
  File "/Library/Python/2.7/site-packages/chattydotfiles/repository.py", line 101, in add
    return ChattyFile(store_filename, filename).add()
  File "/Library/Python/2.7/site-packages/chattydotfiles/chatty_file.py", line 234, in add
    os.rename(self.home_filename, self.store_filename)
OSError: [Errno 2] No such file or directory
```

**Comment by jamescooke** [comment] 2015-02-20 17:37
Thanks @jonashaefele I'll check it out.

**Comment by jamescooke** [comment] 2015-11-13 13:25
Can confirm that this works on zsh on linux - so I either need a mac to test on, or some input from someone running on a mac. Ideally I'd like to know what `home_filename` is inside that instance of `ChattyFile` and I might add a debugging flag to help get that information out at runtime.

**Comment by jamescooke** [comment] 2015-11-24 16:04
Hi @jonashaefele - I've spotted the problem, and I'm surprised it's taken me this long, sorry. The issue is that you're already inside your store `~/dotfiles/store` when you run `chattydotfiles --add`. This creates the crash.

The program should respond nicely to you instead of crashing. I'll file an issue for that and make the required improvements.

**Comment by jonashaefele** [comment] 2015-11-24 20:07
Oh, thanks a ton!  Glad you found the root of it.  More chatter for my dot
files!

**Comment by jamescooke** [comment] 2017-01-23 11:09
Closing this project in preference for using `stow` - see https://alexpearce.me/2016/02/managing-dotfiles-with-stow/

Thanks for the feedback @jonashaefele - I just haven't had the time to push this utility forwards.

**Closed by jamescooke** 2017-01-23 11:09 UTC
Labels: wontfix
